export const music = [
  {
    title: "Hold You Like a Secret",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/1A2EJiDq6JzqLxs0V6BrBl?si=abd56a3f74d04ff9",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/hold-you-like-a-secret",
    musicIcon: true,
  },
  {
    title: "S.O.S",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/5xAnaQAWecqo3IpNjM9hKW?si=375a44965a834f7c",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/sos",
    musicIcon: true,
  },
  {
    title: "Beccas Song",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/5uHEWu6AWbrlIOrkxl8JKh?si=1a478aa20e7a461a",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/beccas-song",
    musicIcon: true,
  },
  {
    title: "Happy Ever After",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/4ArRymlVaLt722cES9BFqv?si=245fd8a43e264aeb",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/happy-ever-after",
    musicIcon: true,
  },
  {
    title: "Catch 22",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/3COXmEgoC1WUBrYSUFiYJI?si=cf9b66cf48c74928",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/catch22",
    musicIcon: true,
  },
  {
    title: "Love Me or Leave Me",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/4Y3a3C0uCqJdXIhXzGOtPg?si=7abf1740425a4d72",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/love-me-or-leave-me",
    musicIcon: true,
  },
  {
    title: "Liar",
    duration: "2:21",
    artwork: "/avatar.png",
    tidal: "",
    spotify:
      "https://open.spotify.com/track/6wSbwYohLqt8nKfUueAZ88?si=f4cc25e63f364abb",
    appleMusic: "",
    amazonMusic: "",
    itunes: "",
    href: "/liar",
    musicIcon: true,
  },
];
